language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: false

cache: pip

install:
  - pip install tox codecov

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

after_success:
  - codecov

notifications:
  email:
    recipients:
      - wangbinxin001@126.com
    on_success: always
    on_failure: always
